project:
  type: website
  output-dir: docs

website:
  description: "Final Project for EDLD 652"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Arts Education Nonprofits"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/stmii
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css



editor: visual

